// Component Imports
import Header from "@/components/header/components/Header";
import Footer from "@/components/footer/components/Footer";

// Package Imports
import type { Metadata } from "next";

// CSS Imports
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-roboto">
        <Header />
        <main className="mt-20">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
